baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Mole Cave"
[outputs]
home = ['html', 'rss']
section = ['html', 'rss']
taxonomy = ['html']
term = ['html']

[markup.goldmark.renderer]
    unsafe = true
