name: GitHub Actions Demo
run-name: ${{ github.actor }} is updating his website ;3
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v6
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.163.3"

      - name: Build Website
        run: |
          hugo build

      - name: Copy SSH key
        run: |
          mkdir -p ~/.ssh
              echo "${{ secrets.PI_PUBLIC_KEY }}" > ~/.ssh/id_ed25519.pub
              chmod 600 ~/.ssh/id_ed25519.pub

      - name: Tailscale Connection
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_CLIENT_SECRET }}
          tags: tag:cd

      - name: Sync the files
        run: |
          rsync -a ./public/ mole@100.88.185.69:${{ secrets.WEBSITE_PATH }}

      - name: restart the compose
        run: |
          docker compose restart molecave
