name: GitHub Actions Demo
run-name: ${{ github.actor }} is updating his website ;3
on: [push]
jobs:
  Hugo-GitHub-Action:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.163.3"

      - name: Build Website
        run: |
          hugo build

      - name: Copy SSH key
        run: |
          mkdir -p ~/.ssh
              echo "${{ secrets.PI_PUBLIC_KEY }}" > ~/.ssh/id_ed25519
              chmod 600 ~/.ssh/id_ed25519

      - name: Tailscale Connection
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_CLIENT_SECRET }}
          tags: tag:cd
          ephemeral: true

      - name: Sync the files
        run: |
          rsync -rlz --delete --no-times --no-perms -e "ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no" ./public/ mole@100.88.185.69:${{ secrets.WEBSITE_PATH }}
